"""add relationships

Revision ID: 3eaeb896a397
Revises: a50f51724135
Create Date: 2023-04-01 16:07:34.051416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eaeb896a397'
down_revision = 'a50f51724135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_course_level_id_level'), 'level', ['level_id'], ['id_'])

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('uploader_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_document_uploader_id_moderator'), 'moderator', ['uploader_id'], ['id_'])
        batch_op.create_foreign_key(batch_op.f('fk_document_course_id_course'), 'course', ['course_id'], ['id_'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_document_course_id_course'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_document_uploader_id_moderator'), type_='foreignkey')
        batch_op.drop_column('uploader_id')
        batch_op.drop_column('course_id')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_course_level_id_level'), type_='foreignkey')
        batch_op.drop_column('level_id')

    # ### end Alembic commands ###
