"""add unique constraint to Level name

Revision ID: 4676d8766008
Revises: 3eaeb896a397
Create Date: 2023-04-03 18:22:09.736728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4676d8766008'
down_revision = '3eaeb896a397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('level', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_level_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('level', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_level_name'), type_='unique')

    # ### end Alembic commands ###
