"""add RBAC fields

Revision ID: 4fd857dae0c9
Revises: f534cdc1e691
Create Date: 2023-06-24 18:47:21.273296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd857dae0c9'
down_revision = 'f534cdc1e691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderator', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        #batch_op.add_column(sa.Column('role_number', sa.Integer(), nullable=True))
        pass
    # op.execute("UPDATE moderator SET is_admin = false")
    # op.execute("UPDATE moderator SET role_number = 1")
    op.alter_column('moderator', 'is_admin', nullable=False)
    op.alter_column('moderator', 'role_number', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderator', schema=None) as batch_op:
        batch_op.drop_column('role_number')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
