"""Add email verification field

Revision ID: 65edbd6d8afe
Revises: a0b8ae7d5c78
Create Date: 2023-09-26 23:56:55.813770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65edbd6d8afe'
down_revision = 'a0b8ae7d5c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_on', sa.DateTime(), nullable=True))

    with op.batch_alter_table('moderator', schema=None) as batch_op:
        batch_op.execute("UPDATE moderator SET email_verified = false")
        batch_op.alter_column('email_verified', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderator', schema=None) as batch_op:
        batch_op.drop_column('confirmed_on')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
