"""empty message

Revision ID: 97e17fdeeae1
Revises: 4fd857dae0c9
Create Date: 2023-06-24 19:24:14.840087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e17fdeeae1'
down_revision = '4fd857dae0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderator', schema=None) as batch_op:
        batch_op.alter_column('role_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderator', schema=None) as batch_op:
        batch_op.alter_column('role_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
