"""first migration

Revision ID: a50f51724135
Revises: 
Create Date: 2023-03-18 17:22:08.048394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50f51724135'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_course_course_title'), ['course_title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_course_course_title'), type_='unique')

    # ### end Alembic commands ###
