"""Remove username uq constraint

Revision ID: ae8bf2aa98d9
Revises: 65edbd6d8afe
Create Date: 2023-10-06 22:18:58.392808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8bf2aa98d9'
down_revision = '65edbd6d8afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderator', schema=None) as batch_op:
        batch_op.drop_constraint('uq_moderator_username', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderator', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_moderator_username', ['username'])

    # ### end Alembic commands ###
