"""add Role relationship

Revision ID: b3135c692393
Revises: 97e17fdeeae1
Create Date: 2023-06-25 23:55:29.021897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3135c692393'
down_revision = '97e17fdeeae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderator', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('role_number')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_number', sa.INTEGER(), nullable=False))
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
