"""update course model

Revision ID: df7200c09a90
Revises: ae8bf2aa98d9
Create Date: 2023-12-31 01:19:27.895422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7200c09a90'
down_revision = 'ae8bf2aa98d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('contributor_id', sa.Integer(), nullable=True))
        # batch_op.drop_index('ix_course_course_code')
        batch_op.create_foreign_key(batch_op.f('fk_course_contributor_id_moderator'), 'moderator', ['contributor_id'], ['id_'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_course_contributor_id_moderator'), type_='foreignkey')
        batch_op.create_index('ix_course_course_code', ['course_code'], unique=False)
        batch_op.drop_column('contributor_id')
        batch_op.drop_column('added_on')

    # ### end Alembic commands ###
